### ISSUE TITLE
Code review 2

### ISSUE THREAD

**Issue by aitoAarni** [Veloxization/activity-calendar#2]
2.
- Ulkoasku on erinomainen, muutamaa elemnttiä lukuunottamatta
- helppo navigoida
- suurilta osin valmis
3.
- Koodi siistiä ja selkeästi ymmärrettävää
- Koodi hyvin paketoitu moduuleiksi
- Kaikki toiminnallisuudet eivät vielä toimi, kuten viestit ja aktiviteettien hyväksyminen

**Comment by Veloxization** [comment]
Ulkoasua on korjattu, ongelmia oli erityisesti pitkien sivujen kanssa. Loput toiminnallisuudet on myös toteutettu.

Kiitos paljon palautteesta!
